---
title: "CountsimQC of simulated scRNA-seq data"
author: "Carissa Chen and Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
Generate countsimQC report of simulated scRNA-seq data.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(dplyr)
  library(splatter)
  library(plyexperiment)
  library(countsimQC)
  library(DESeq2)
})
```

## Load 3-class cellbench data
```{r}
load("../../../Data/cellbench_sce_3class.RData", verbose=T)
rm(sce_CELseq2_log)
rm(sce_Dropseq_log)
```

## Source functions
```{r}
source("../../../R/simulateDS.R")
source("../../../R/Cepo.R")
```

# Simulate scRNA-seq data
Note that this part has been run on server (set.seed gives different output)
```{r}
## generate simulation parameters 
cellbch = sce_10x_log
cellbch_sub = cellbch %>% filter_col(celltype %in% c("H1975", "H2228"))
params <- splatEstimate(cellbch_sub)

## simulate scRNA-seq data
set.seed(123)
sim <- splatSimulate(params, 
                     nGenes = 10000, 
                     batchCells = c(100),
                     method = "single") %>% 
  scater::logNormCounts()

save(cellbch_sub, sim, 
     file = "../../../Data/210421_simulation_count.RData")
```

# Generate countsimQC report
```{r}
labels = factor(rep(c("A", "B"), each = 50))
dds <- DESeqDataSetFromMatrix(countData = counts(sim), 
                              colData = S4Vectors::DataFrame(labels),
                              design = ~labels)

labels2= factor(cellbch_sub$celltype)
original <- DESeqDataSetFromMatrix(countData = counts(cellbch_sub), 
                              colData = S4Vectors::DataFrame(labels2),
                              design = ~labels2)

ddslist <- list(original=original, sim1=dds)

countsimQCReport(ddsList = ddslist, 
                 outputFile = "countsimReport_CepoData.html", 
                 outputDir = "../", 
                 description = "report of Cepo simulated data")
```

# Session Info
```{r}
sessioninfo::session_info()
```
