---
title: "Cellbench scatter plot of differential analysis statistics"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script generates scatter plot of the ranked differential statistics generated using the benchmarked differential analysis methods. 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(GGally)
  library(RColorBrewer)
  library(ggplot2)
  library(ggthemes)
  library(dplyr)
})
```

## Load 3-class cellbench data and dx results
```{r}
load("../../../Data/cellbench_sce_3class.RData", verbose=T)
rm(sce_CELseq2_log)
rm(sce_Dropseq_log)

load("../../../Data/cellbench_DE_benchmark_results.RData", verbose=T)
load("../../../Data/cellbench_Dx_benchmark_results.RData", verbose=T)
load("../../../Data/cellbench_Seurat_benchmark_results.RData", verbose=T)
load("../../../Data/cellbench_SCVI_benchmark_results.RData", verbose=T)
load("../../../Data/cellbench_M3Drop_benchmark_results.RData", verbose=T)
```

## Source functions
```{r}
source("../../../R/utils.R")
```

# Calculate stability scores
```{r}
exprsMat <- logcounts(sce_10x_log)
celltype <- factor(sce_10x_log$celltype)

zprop <- apply(exprsMat, 1, function(x) length(x[x==0])/length(x))
cv <- apply(exprsMat, 1, function(x) sd(x)/mean(x))
```

# Plot pairwise scatter plot of ranks
```{r}
ggstability_ranked <- lapply(levels(celltype), function(i) {
  
  idx <- names(cv)
  df=data.frame(Cepo=rank(DS.res[[i]])[idx],
                Voom=rank(Voom.res[[i]])[idx],
                Limma=rank(Limma.res[[i]])[idx],
                ttest=rank(ttest.res[[i]])[idx],
                EdgeR=rank(EdgeR.res[[i]])[idx],
                ROC=rank(ROC.res[[i]])[idx],
                MAST=rank(MAST.res[[i]])[idx],
                Wilcoxon=rank(Wilcoxon.res[[i]])[idx],
                DD=rank(DD.res[[i]])[idx],
                #M3Drop=rank(M3DROP.res[[i]])[idx],
                SCVI=rank(SCVI.res[[i]])[idx],
                Bimod=rank(Bimod.res[[i]])[idx],
                LR=rank(LR.res[[i]])[idx],
                zprop=zprop[idx])
  rownames(df) = idx
  
  
  return(df)
  
})
names(ggstability_ranked) <- levels(celltype)

lapply(levels(celltype), function(i) {
  
  type <- i
  GGally::ggpairs(ggstability_ranked[[i]],
                  1:12,
                  lower = list(continuous = wrap(GGscatterPlot, color_vec=ggstability_ranked[[i]]$zprop)),
                  upper = list(continuous = wrap("cor", method= "pearson"))) %>% ggsave(filename=paste0("../../../Figures/cellbench/cellbench_ggpairs_stability_210429", type,".pdf"), width=15, height=15)
  
})
```

```{r}
ggstability_ranked <- lapply(levels(celltype), function(i) {
  
  idx <- names(cv)
  df=data.frame(Cepo=DS.res[[i]][idx],
                Voom=Voom.res[[i]][idx],
                Limma=Limma.res[[i]][idx],
                ttest=ttest.res[[i]][idx],
                EdgeR=EdgeR.res[[i]][idx],
                ROC=ROC.res[[i]][idx],
                MAST=MAST.res[[i]][idx],
                Wilcoxon=Wilcoxon.res[[i]][idx],
                DD=DD.res[[i]][idx],
                #M3Drop=rank(M3DROP.res[[i]])[idx],
                SCVI=SCVI.res[[i]][idx],
                Bimod=Bimod.res[[i]][idx],
                LR=LR.res[[i]][idx],
                zprop=zprop[idx])
  rownames(df) = idx
  
  
  return(df)
  
})
names(ggstability_ranked) <- levels(celltype)

lapply(levels(celltype), function(i) {
  
  type <- i
  GGally::ggpairs(ggstability_ranked[[i]],
                  1:12,
                  lower = list(continuous = wrap(GGscatterPlot, color_vec=ggstability_ranked[[i]]$zprop)),
                  upper = list(continuous = wrap("cor", method= "spearman"))) %>% ggsave(filename=paste0("../../../Figures/cellbench/cellbench_ggpairs_stability2_210429", type,".pdf"), width=15, height=15)
  
})
```


# Session Info
```{r}
sessioninfo::session_info()
```
